### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by xwshan** [jwchoi384/Gaussian_YOLOv3#16]

**Comment by xwshan** [comment]
Hi, it's really a good project.

I am training the network according to the steps of yolov3. It is normal to start training, but -nan appears when batch=1000 or so, it cannot be calculated normally.

Is data preparation different from yolov3?

Thanks a lot.

**Comment by jwchoi384** [comment]
@maibaozhidelangzi 
Hi, 
Data preparation is same as YOLOv3.
In that case, try again.
It is different each time you run it because weight is initialized randomly.
If it fail again, increase the burn-in value in the cfg file or decrease the learning rate.
In my experience, because of the variance value, early training is difficult. 
So you need to try several times.
